
- name: wait for hss start if current service is mme
  wait_for:
    host: "{{HSS_IP}}"
    port: 22
    state: started
    delay: 10
  when: TARGET_SERVICE == "mme"

- name: wait for mme start if current service is spgw
  wait_for:
    host: "{{MME_IP}}"
    port: 22
    state: started
    delay: 10
  when: TARGET_SERVICE == "spgw"